# Configuration file
steamdb_url: "https://steamdb.info/sales/"
bigquery_project_id: "seu_projeto_id"
bigquery_dataset: "steamdb_dataset"
bigquery_table: "sales"
chromedriver_path: "/caminho/para/chromedriver"
